# Generated by Django 2.2.8 on 2019-12-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Adı')),
                ('author_image', models.ImageField(upload_to='images/authors', verbose_name='Şekili')),
                ('gender', models.IntegerField(choices=[(1, 'Kişi'), (2, 'Qadın')], default=1, verbose_name='Cinsiyyeti')),
                ('date_of_birth', models.DateField(verbose_name='Doğum Tarixi')),
                ('nationality', models.CharField(max_length=255, verbose_name='Milliyeti')),
                ('info', models.TextField(verbose_name='Haqqında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ('fullname',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('page_count', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='images/books')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Author')),
                ('category', models.ManyToManyField(to='myapp.Category')),
            ],
            options={
                'verbose_name': 'Kitab',
                'verbose_name_plural': 'Kitablar',
                'ordering': ('title',),
            },
        ),
    ]
